export {
  EMPTY_TEXT,
  formatDateDisplay,
  formatEmailValue,
  formatIndonesianPhoneNumber,
  formatNumberDisplay,
  fromDateTimeLocalInputValue,
  fromMultiPicklistSelectOptions,
  getFieldInputFlags,
  isRichTextField,
  isTextAreaField,
  MULTI_PICKLIST_SEPARATOR,
  readAddressDisplayValue,
  readCompoundObject,
  readLocationDisplayValue,
  readLocationHref,
  readNameDisplayValue,
  readReferenceHref,
  readTextValue,
  resolveReadOnlyValue,
  toDateInputValue,
  toDateTimeLocalInputValue,
  toMultiPicklistArray,
} from './fieldShared.js'
