export const boardItems = [
  {
    id: 'meme',
    icon: '😂',
    title: 'Meme internal',
    description: 'Kumpulan meme yang cuma circle kalian yang paham konteksnya.',
    note: 'Saved 12 times',
    tone: 'from-amber-300 to-orange-400',
    examples: [
      {
        id: 'meme-1',
        art: '🤣',
        sender: 'Joshua',
        time: '09:14',
        title: 'Joshua tiap bilang "OTW"',
        caption: 'Padahal masih mandi dan baru cari kaos.',
      },
      {
        id: 'meme-2',
        art: '⏰',
        sender: 'Bayu',
        time: '19:02',
        title: 'Alarm rapat circle jam 7',
        caption: 'Semua baca, semua mute, tidak ada yang join tepat waktu.',
      },
      {
        id: 'meme-3',
        art: '🫥',
        sender: 'Ryan',
        time: '22:16',
        title: 'Mode silent pas ditag',
        caption: 'Aktif di grup lain, tapi begitu ditanya langsung menghilang.',
      },
    ],
  },
  {
    id: 'joke',
    icon: '🤣',
    title: 'Joke teman',
    description: 'Quote receh, punchline absurd, dan candaan khas tongkrongan.',
    note: 'Hot this week',
    tone: 'from-fuchsia-400 to-pink-500',
    examples: [
      {
        id: 'joke-1',
        art: '🎤',
        sender: 'Bayu',
        time: '11:08',
        title: 'Bayu: "Aku serius"',
        caption: 'Kalimat yang selalu muncul sebelum semua orang ketawa.',
      },
      {
        id: 'joke-2',
        art: '🫠',
        sender: 'Angga',
        time: '08:21',
        title: 'Angga typo legendaris',
        caption: '"Semnagat" sekarang jadi quote wajib tiap pagi.',
      },
      {
        id: 'joke-3',
        art: '😌',
        sender: 'Joshua',
        time: '20:04',
        title: 'Percaya diri tanpa alasan',
        caption: '"Tenang, aku hafal jalan" lalu tetap nyasar dua kali.',
      },
    ],
  },
  {
    id: 'screenshot',
    icon: '📸',
    title: 'Screenshot lucu',
    description: 'Chat random, typo ikonik, dan momen yang tidak boleh hilang.',
    note: 'Archive ready',
    tone: 'from-sky-400 to-cyan-500',
    examples: [
      {
        id: 'screenshot-1',
        art: '💬',
        sender: 'Ryan',
        time: '02:07',
        title: 'Chat jam 2 pagi',
        caption: 'Thread debat mie instan yang berakhir jadi sharing hidup.',
      },
      {
        id: 'screenshot-2',
        art: '📱',
        sender: 'Vina',
        time: '22:41',
        title: 'Voice note salah kirim',
        caption: 'Momen paling chaos yang masih sering di-replay.',
      },
      {
        id: 'screenshot-3',
        art: '📷',
        sender: 'Bayu',
        time: '18:27',
        title: 'Screenshot chat setengah sadar',
        caption: 'Balasan yang dikirim terlalu cepat dan langsung disesali.',
      },
    ],
  },
]
