export const moodOptions = [
  {
    id: 'happy',
    emoji: '😄',
    label: 'senang',
    accent: 'from-emerald-400 to-teal-500',
    headline: 'Lagi happy hari ini',
    subtext: 'Mood lagi ringan dan pengen menikmati hari.',
    frame: '╔ SUNNY CHECK-IN ╗',
    divider: '☼ ☼ ☼',
    quickNote: 'Quick note: Hari ini vibes-nya lagi enak.',
  },
  {
    id: 'excited',
    emoji: '🤩',
    label: 'antusias',
    accent: 'from-amber-400 to-orange-500',
    headline: 'Energi lagi naik',
    subtext: 'Lagi semangat buat jalanin banyak hal seru.',
    frame: '╔ HYPE CHECK-IN ╗',
    divider: '✦ ✦ ✦',
    quickNote: 'Quick note: Kalau energinya nular, jangan kaget.',
  },
  {
    id: 'productive',
    emoji: '😎',
    label: 'produktif',
    accent: 'from-sky-500 to-indigo-600',
    headline: 'Lagi on fire',
    subtext: 'Pengen fokus dan beresin banyak hal hari ini.',
    frame: '╔ FOCUS CHECK-IN ╗',
    divider: '• WORK MODE •',
    quickNote: 'Quick note: Hari ini maunya gerak maju terus.',
  },
  {
    id: 'biasa',
    emoji: '😐',
    label: 'biasa',
    accent: 'from-slate-400 to-slate-500',
    headline: 'Hari ini santai aja',
    subtext: 'Nggak terlalu tinggi, nggak terlalu rendah, jalan pelan-pelan aja.',
    frame: '╔ DAILY CHECK-IN ╗',
    divider: '· · ·',
    quickNote: 'Quick note: Hari ini dijalani setenang mungkin.',
  },
  {
    id: 'capek',
    emoji: '😮‍💨',
    label: 'capek',
    accent: 'from-stone-400 to-slate-600',
    headline: 'Energi lagi turun',
    subtext: 'Butuh jeda sebentar dan pengen ambil napas dulu.',
    frame: '╔ SLOW CHECK-IN ╗',
    divider: '⋯ ⋯ ⋯',
    quickNote: 'Quick note: Respon pelan bukan berarti menghilang.',
  },
  {
    id: 'males',
    emoji: '🥱',
    label: 'males',
    accent: 'from-zinc-400 to-stone-600',
    headline: 'Mode hemat energi',
    subtext: 'Hari ini pengennya gerak seperlunya aja.',
    frame: '╔ LOW BATTERY MODE ╗',
    divider: 'z z z',
    quickNote: 'Quick note: Hari ini mode hemat energi aktif.',
  },
  {
    id: 'ngantuk',
    emoji: '😴',
    label: 'ngantuk',
    accent: 'from-indigo-400 to-blue-500',
    headline: 'Mata udah berat',
    subtext: 'Kalau responnya agak lambat, berarti lagi berjuang lawan kantuk.',
    frame: '╔ SLEEPY CHECK-IN ╗',
    divider: 'zzZ zzZ',
    quickNote: 'Quick note: Kalau typo, anggap saja sedang merem.',
  },
  {
    id: 'sedih',
    emoji: '😭',
    label: 'sedih',
    accent: 'from-blue-400 to-slate-500',
    headline: 'Lagi sendu hari ini',
    subtext: 'Sedang butuh ruang, tenang, atau teman ngobrol.',
    frame: '╔ SOFT CHECK-IN ╗',
    divider: '｡ ｡ ｡',
    quickNote: 'Quick note: Hari ini butuh yang lembut-lembut saja.',
  },
  {
    id: 'anxious',
    emoji: '😵‍💫',
    label: 'cemas',
    accent: 'from-violet-500 to-fuchsia-600',
    headline: 'Pikiran lagi ramai',
    subtext: 'Sedikit overthinking, jadi lagi butuh ritme yang lebih pelan.',
    frame: '╔ CALM-DOWN CHECK-IN ╗',
    divider: '° ° °',
    quickNote: 'Quick note: Pelan-pelan juga tetap jalan.',
  },
  {
    id: 'bad-mood',
    emoji: '😡',
    label: 'kesal',
    accent: 'from-rose-500 to-orange-500',
    headline: 'Mood lagi kurang enak',
    subtext: 'Kalau hari ini terasa lebih sensitif, itu memang lagi bagian dari harinya.',
    frame: '╔ MOOD ALERT ╗',
    divider: '! ! !',
    quickNote: 'Quick note: Hari ini lebih aman pakai nada lembut.',
  },
]

export const friendsSeed = [
  { name: 'Joshua', gender: 'pria', moodId: 'ngantuk' },
  { name: 'Bayu', gender: 'pria', moodId: 'productive' },
  { name: 'Angga', gender: 'pria', moodId: 'bad-mood' },
]
